### ISSUE TITLE
After Update fblitho to 0.13.1 PicassoImage stop working.

### ISSUE THREAD

**Issue by sergiosena** [charbgr/litho-picasso#1]
Hi, after update Facebook Litho to 0.13.1 version I'm getting this error:

```
java.lang.IllegalAccessError: Method 'void com.facebook.litho.ComponentLifecycle.<init>()' is inaccessible to class 'com.github.charbgr.litho.picasso.PicassoImage' (declaration of 'com.github.charbgr.litho.picasso.PicassoImage' appears in /data/app/com.listtu.app-1/base.apk)
        at com.github.charbgr.litho.picasso.PicassoImage.<init>(PicassoImage.java:65)
        at com.github.charbgr.litho.picasso.PicassoImage.get(PicassoImage.java:70)
        at com.github.charbgr.litho.picasso.PicassoImage$PicassoImageImpl.<init>(PicassoImage.java:265)
        at com.github.charbgr.litho.picasso.PicassoImage$PicassoImageImpl.<init>(PicassoImage.java:173)
        at com.github.charbgr.litho.picasso.PicassoImage.create(PicassoImage.java:166)
        at com.github.charbgr.litho.picasso.PicassoImage.create(PicassoImage.java:170)
```

Is anyone facing this issue?

**Comment by charbgr** [comment]
Hi @sergiosena.

I am facing some issues with maven repository. I cannot upload snapshot right now.

Can you please check out this [branch](https://github.com/charbgr/litho-picasso/tree/charbgr/upgrade_litho) till I fix them?

**Comment by sergiosena** [comment]
Ofcourse! I'll write back after test it soon.
Thanks!!!

**Comment by sergiosena** [comment]
Worked like a charm! 😃
Thank you very much.
